version: '3.1'
services:
  db:
    image: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file: .env
    ports:
      - "8080:80"
